// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTuSKL9Y4AzQDvyJJvMhRP315Jj0f1MFM',
    appId: '1:295775124303:web:060f65b1086f4bc6a4233a',
    messagingSenderId: '295775124303',
    projectId: 'saviaqua-b85dd',
    authDomain: 'saviaqua-b85dd.firebaseapp.com',
    storageBucket: 'saviaqua-b85dd.firebasestorage.app',
    measurementId: 'G-WCL2QCQHF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASN58jW1HatjbiMsjXCeSJTqbuXhAhmIU',
    appId: '1:295775124303:android:5d03f6dee07254fba4233a',
    messagingSenderId: '295775124303',
    projectId: 'saviaqua-b85dd',
    storageBucket: 'saviaqua-b85dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKLPyfev2RYGQZ3mFhr0iJMfFuBuLwaew',
    appId: '1:295775124303:ios:a14b51d49114ad8ea4233a',
    messagingSenderId: '295775124303',
    projectId: 'saviaqua-b85dd',
    storageBucket: 'saviaqua-b85dd.firebasestorage.app',
    iosBundleId: 'com.example.saviaqua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKLPyfev2RYGQZ3mFhr0iJMfFuBuLwaew',
    appId: '1:295775124303:ios:a14b51d49114ad8ea4233a',
    messagingSenderId: '295775124303',
    projectId: 'saviaqua-b85dd',
    storageBucket: 'saviaqua-b85dd.firebasestorage.app',
    iosBundleId: 'com.example.saviaqua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTuSKL9Y4AzQDvyJJvMhRP315Jj0f1MFM',
    appId: '1:295775124303:web:920fa95f6d3f75d9a4233a',
    messagingSenderId: '295775124303',
    projectId: 'saviaqua-b85dd',
    authDomain: 'saviaqua-b85dd.firebaseapp.com',
    storageBucket: 'saviaqua-b85dd.firebasestorage.app',
    measurementId: 'G-BBKR9M2VDG',
  );
}
